### ISSUE TITLE
Docs is not updated to v0.7.0-rc2

### ISSUE THREAD

**Issue by lezzokafka** [crypto-org-chain/cronos-testnets#9]
Solution: 
Similar to #8  - 
- Update Testnet Status https://github.com/crypto-org-chain/cronos-testnets#testnet-status
- Add v0.7-rc2 to the latest version  https://github.com/crypto-org-chain/cronos-testnets/blob/main/testnet.json, while keeping the old `v0.6.*`, `v0.7-rc1`

**Comment by lezzokafka** [comment]
https://github.com/crypto-org-chain/cronos/releases/tag/v0.7.0-rc2

**Comment by aw126** [comment]
Updated with https://github.com/crypto-org-chain/cronos-testnets/commit/1c64103bb217ffd8695cc2be6bf683a8fa7453e2 & https://github.com/crypto-org-chain/cronos-testnets/commit/4be2685f70a12c743895b1d6492b9aaf0a411006
